version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run: 
          name: Install golint package
          command: go get -u golang.org/x/lint/golint

      - run:
          name: Lint Test
          command: golint app/