version: 2
jobs:
  build:
    branches:
      only:
        - /feature/*
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run:
          name: Lint Test
          command: golint app/