apiVersion: v1
kind: Service
metadata:
  name: kube-hello
  namespace: kube-hello
spec:
  selector:
    app: kube-hello
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort